### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by anderssv** [adriank/ObjectPath#28]
All the links for docs on the main site giver 404

**Comment by anderssv** [comment]
Yes. One example is the Tutorial link midway down that leads to http://objectpath.org/ObjectPath/tutorial.html which gives a 404. :)

**Comment by adriank** [comment]
I can't reproduce this behavior. Are you sure it's not redirecting you to github.io/ObjectPath at some point?

**Comment by anderssv** [comment]
Nope, doesn't look like it. Just tested from a completely new location now, and still 404.

**Comment by adriank** [comment]
What browser do you use?

**Comment by anderssv** [comment]
Chrome 40.0.2214.93 (64-bit), Ubuntu . At least at this location, but should be same at other. :)

**Comment by anderssv** [comment]
Weird. Check out this video: https://docs.google.com/file/d/0B_2uqwKdjo74alVCSTFLcEZUMGc/edit?pli=1

Doesn't show the URLs, but they are the same as we talked about earlier.

**Comment by adriank** [comment]
Hmmm, can you check if clearing your browser cache helps? There is no
/ObjectPath/ in HTML files right now, but half year ago the URL to this
site was adriank.github.io/ObjectPath and indeed every link was prefxed
with /ObjectPath. If not then it seems it's issue with github.io.

**Comment by anderssv** [comment]
Ah, yes now it's working. Weird though, I accessed ObjectPath for the first time a couple of days ago. And different computers so should be different caches too. :)
