### ISSUE TITLE
$.* does not show the no. of undisplayed objects

### ISSUE THREAD

**Issue by ela-b** [adriank/ObjectPath#3]
I type $.\* and I get the 3 first objects, but there's no info about how many more remain undisplayed. In the case below, it should say "there are 2 more objects" or sth like that. 
![topics](https://cloud.githubusercontent.com/assets/2857448/3348507/a1854d08-f931-11e3-8236-6f8f81d5d579.png)

**Comment by davide-romanini** [comment]
How do I see all selected objects? It shows only first 5, there should be an option to show all results..

**Comment by adriank** [comment]
Try:

all $.*
