### ISSUE TITLE
tutorial link gives 404

### ISSUE THREAD

**Issue by gsauthof** [adriank/ObjectPath#40]
On the start page (i.e. https://adriank.github.io/ObjectPath/), clicking on the tutorial link (i.e. https://adriank.github.io/tutorial.html) results in a 404 ('There isn't a GitHub Pages site here.').

**Comment by adriank** [comment]
Hi,

The proper URL of the project is http://objectpath.org. I'll investigate
why autoredirect doesn't work.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co/ <http://about.me/akalbarczyk>

**Comment by gsauthof** [comment]
I see.

The URL https://adriank.github.io/ObjectPath/ was the second google result when I searched for 'python json query'.

**Comment by adriank** [comment]
Redirect should work now.
