### ISSUE TITLE
Can't interpret object keys which contain ":"

### ISSUE THREAD

**Issue by richard-jones** [adriank/ObjectPath#42]
I have a JSON-LD style document that contains ":" as a namespace separator in the object's keys, so something like:

```json
{
    "dc:identifier" : [{"type" : "identifier type", "id" : "identifier"}]
}
```

When I do 

    t = Tree(doc)
    t.execute("$.dc:identifier")

I get nothing back.

If I add a key which does not have a ":" it works fine, so I guess that's the reason.

I couldn't see if ":" is a special character in objectpath, and I couldn't find an escape character to use from the documentation, so a bit stuck.  A shame, as it does everything else I need!

**Comment by adriank** [comment]
t.execute("$.'dc:identifier'") should solve that. :)

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co <http://about.me/akalbarczyk>

**Comment by richard-jones** [comment]
Excellent!  Works nicely, thank you :)
