### ISSUE TITLE
Support querying python objects

### ISSUE THREAD

**Issue by Evgenus** [adriank/ObjectPath#50]
Any plans to support? 
I would like to
```
>>> import datetime
>>> import objectpath
>>> objectpath.Tree(datetime).execute("$.*.now")
```

**Comment by adriank** [comment]
Can you write how you'd like it to work? Code example would be best.

**Comment by Evgenus** [comment]
```
$.attr  -  matches object attribute 
$[attr]  -  matches dictionary key
$.*  -  matches any attribute
$.**  -  same recursively
$[*]  -  matches any dictionary key 
$[**]  -  same recursively
```

attribute matching should be implemented via `hasattr`/`getattr`
dictionary key matching should work for any object that implements `collections.abs.Mapping`

Maybe that would require alternative implementation at general..

**Comment by Evgenus** [comment]
@adriank, any answer? Tell me something please. Like "won't fix" or "not in my project" or whatever you decide.

**Comment by adriank** [comment]
@Evgenus Sorry for the late response.

The purpose of ObjectPath is to simplify work with huge nested structures, mainly JSON, retrieved from some APIs or from databases such as MongoDB. Descent and recursive descent operators are very basic features of the language. You can implement functions to extract information from Python objects within a few hours. 

I believe there isn't a strong case for including them in ObjectPath as it wouldn't serve the community who uses ObjectPath as a tool for speeding up their data mining exercises.
