### ISSUE TITLE
Recursion?

### ISSUE THREAD

**Issue by khusseini** [adriank/ObjectPath#53]
Hey there, I was wondering if it was possible to do recursion of expressions? 

Like so:
```
{
  attachments: $.items[ { title: @.name } ]
}
```

Which would result in:
```
[
  { title: somename },
  { title: somename2 }
]
```

**Comment by adriank** [comment]
How your input JSON looks like?

**Comment by khusseini** [comment]
For this case, something like
```
{
   items: [
       { name: somename, other: hello },
       { name: somename2, other: world }
   ]
}
```

**Comment by adriank** [comment]
Unfortunately not. ObjectPath is a query language and your example is a schema conversion task. I thought about extending OP to make it possible, but I did not find enough time to do it.
