### ISSUE TITLE
updating fields through object path

### ISSUE THREAD

**Issue by KageKirin** [adriank/ObjectPath#64]
Hi,
I've been starting to use ObjectPath earlier today, mostly because I'm dissatisfied with existing JsonPath implementations in Python.

I've been looking through the documentation, but could not find anything related to updating fields from their given path. Is there any functionality like this?

Best regards.

**Comment by adriank** [comment]
Hi,

ObjectPath is a query language. Updating is not possible.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ

**Comment by KageKirin** [comment]
Fair enough.
Thanks for the clear answer.
Cheers.
