### ISSUE TITLE
Jsonpath with multiple array seectors

### ISSUE THREAD

**Issue by hrushikesh198** [adriank/ObjectPath#65]
How to write jsonpath when multiple array selectors are required?
In the bellow `python` example the I want to select ` {"d": 10, "e": 20}` first jsonpath looks correct but does not work. The other ones have side effects. 
```
from objectpath import Tree
a={ 
    "a": [
        {
            "b":1,
            "c": [
                {"d": 10, "e": 20},
                {"d": 30, "e": {"d": 10, "e": 11}},
            ],
            "b2": {
                "c":[
                    {"d":10, "e": 12}
                ]
            }
        },
        {"b": 2}
    ]
}
print list(Tree(a).execute("$.a[@.b is 1].c[@.d is 10]"))
print list(Tree(a).execute("$.a[@.b is 1].c..*[@.d is 10]"))
print list(Tree(a).execute("$.a[@.b is 1]..c[@.d is 10]"))
Output:
[]
[{'e': 20, 'd': 10}, {'e': 11, 'd': 10}]
[{'e': 20, 'd': 10}, {'e': 12, 'd': 10}]
```

**Comment by adriank** [comment]
I don't remember exactly why, but $.a[@.b is 1].c returns [[{'e': 20,
'd': 10}, {'e': 11, 'd': 10}]] so the answer is to add [0] after c
like this:

print list(Tree(a).execute("$.a[@.b is 1].c[0][@.d is 10]"))

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ
