### ISSUE TITLE
Python 3.7, broken on tokenize

### ISSUE THREAD

**Issue by sharksforarms** [adriank/ObjectPath#74]
I'm getting a syntax error no matter what I input. I think this is because tokenize is adding a `NEWLINE` which isn't handled by the core parser.

Getting a `KeyError: 4`  on line 398 in tokenize_python `yield type_map[t[0]], t[1]`

`TokenInfo(type=4 (NEWLINE), string='')` is not handled in the list in the `except KeyError`

`tokenizer.NEWLINE`

**Comment by adriank** [comment]
Unfortunately, I have no access to Python 3.7 right now but last time I had, ObjectPath worked on that version.

**Comment by serjshevchenko** [comment]
Hello, I have the same issue on Python 3.6.7

**Comment by sharksforarms** [comment]
@adriank Any possibility of a release? This will make the package usable on later versions of python
