### ISSUE TITLE
Dynamic concatenation of arrays

### ISSUE THREAD

**Issue by tyjak** [adriank/ObjectPath#76]
Given this data:
```python
{
     "foo": [
          {"bar": [1, 2, 3]},
          {"bar": [4, 5, 6]}
    ]
}
```
Is there a way to concatenate "bar" values in order to obtain a single list like this 
```python 
[1,2,3,4,5,6]
``` 
Obviously this query returns a list of lists
```python
tree.execute('$.foo[bar]')
```

Thanks

**Comment by adriank** [comment]
It's probably impossible. You could add chain function to the ObjectPath.
I'll accept the PR.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ
