### ISSUE TITLE
Average Age of date objects

### ISSUE THREAD

**Issue by TuSKan** [adriank/ObjectPath#81]
Hello, 
In my problem I need to compute the average age of a sub population.

```python
{  
    "peoples":[  
        {  
            "name":"Kelly Robertson",
            "birthDate":"1980-05-11 04:22:33"
        },
        {  
            "name":"Trevin Haley",
            "birthDate":"1985-09-12 12:03:10"
        }
    ]
}
```
It works for 
```python 
avg(age(dateTime($.peoples.birthDate.*[1],'%Y-%m-%d %H:%M:%S')))
``` 
but not for all elements 
```python
avg(age(dateTime($.peoples.birthDate,'%Y-%m-%d %H:%M:%S')))
```

**Comment by adriank** [comment]
$.peoples.birthDate

 is a list, so dateTime won't work. Maybe I should extend map() to accept
parameters. I will think about it.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ
