### ISSUE TITLE
OpenWeatherMap JSON file is broken

### ISSUE THREAD

**Issue by mfdeux** [adriank/ObjectPath#82]
The link on the homepage to http://api.openweathermap.org/data/2.5/box/city?bbox=12,32,15,37,10&cluster=yes returns a 401 response because of an invalid API key.  

```
{
"cod": 401,
"message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."
}
```

**Comment by adriank** [comment]
Register to the service and use the provided API key. They should have free plan.
