### ISSUE TITLE
no list of supported operators

### ISSUE THREAD

**Issue by nebi-frame** [adriank/ObjectPath#98]
Hi all,
I'm not able to find any documentation about all the supported operators for ObjectPath.
For example I've used `matches` operator lots of the time but there's no signle mention for this operator in documentation. Or I'm not able to find it.

**Comment by adriank** [comment]
PRs highly welcomed. :) The intended use of matches is covered in tests:
 
```python
def test_comparison_regex(self):
    self.assertIsInstance(execute("/aaa/"), type(re.compile("")))
    self.assertEqual(execute("/.*aaa/ matches 'xxxaaaadddd'"), True)
    self.assertEqual(execute("'.*aaa' matches 'xxxaaaadddd'"), True)
    self.assertEqual(execute("'.*aaa' matches ['xxxaaaadddd', 'xxx']"), True)```
